export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_USER = 'SET_USER';
export const SET_METHODS_AUTH = 'SET_METHODS_AUTH';
export const SET_PIN_CODE = 'SET_PIN_CODE';
export const SET_AUTHORIZED = 'SET_AUTHORIZED';
export const SET_METHODS_AUTH_DEVICE = 'SET_METHODS_AUTH_DEVICE';
export const SET_USER_GUEST = 'SET_USER_GUEST';
export const SET_CURRENT_LANG = 'SET_CURRENT_LANG';